# allow dev to create a branch from comments
mode: chatops
# close on pull request
autoCloseIssue: true
# create branch and PR at same time
openPR: true
# set develop as the source branch for any label
branches:
  - label: '*'
    name: develop
  
