
name: Create Issue Branch (CIB) [chatops]
on:
    issues:
        types: [assigned]
    issue_comment:
        types: [created]
jobs:
    create_issue_branch_job:
        mode: chatops
        runs-on: ubuntu-latest
        steps:
        - name: Create Issue Branch
          uses: robvanderleek/create-issue-branch@v1.3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        branches:
          - label: '*'
            name: develop