name: VueJs CI

on:
  push:

defaults:
  run:
    working-directory: ./frontend

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Vuejs installation
      run: npm ci
    - name: Run Vuejs Build
      run: npm build
    - name: Run Vuejs unit test
      run: npm test:unit
    - name: Run VueJS Linter
      run: npm run lint
